Sprint 4
RdDevi1/MovieQuiz-ios pull request #2
Opened 2022-10-03 12:17 UTC by RdDevi1

Доброго дня,
вроде получилось выполнить все как требовалось, наибольшая сложность была с реализацией вывода первого вопроса чтобы потом при ответе можно было переходить на второй. Также хотел бы узнать есть ли более лучший вариант отключения рамки при переходе к новому вопросу, чем реализованный у меня - выставление ширины рамки = 0

2022-10-03 18:00 UTC, ABashkirova requested changes
Нужно исправить макет

2022-10-03 18:00 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let viewModel = self.convert(model: firstQuestion)
Тут немного не поняла, зачем тут получать viewModel, если она передается в качестве параметра

2022-10-03 18:00 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let viewModel = self.convert(model: firstQuestion)
У вас вроде было изначально верно, где вы из step доставали значения

2022-10-03 18:00 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.imageView.layer.borderWidth = 0 //скрыть рамку
да, это правильный вариант

2022-10-03 18:00 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.imageView.layer.borderWidth = 0 //скрыть рамку
Также, если вы видите артефакты по краям, еще можно добавить imageView.layer.borderColor = UIColor.clear.cgColor

2022-10-03 18:00 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let viewModel = self.convert(model: firstQuestion)
Эти две строчки должны делаться перед вызовом show, либо вам нужно убрать лишний параметр. 

Однако первый вариант будет легче адаптировать в следующих спринтах. Давайте исправлять

2022-10-05 05:46 UTC, ABashkirova requested changes
Предыдущие комментарии исправлены, осталось два комментария по верстке макетов

2022-10-05 05:46 UTC, ABashkirova commented on MovieQuiz/Resources/Base.lproj/LaunchScreen.storyboard
> +                            <imageView clipsSubviews="YES" userInteractionEnabled="NO" contentMode="scaleAspectFit" horizontalHuggingPriority="251" verticalHuggingPriority="251" image="LaunchScreen"
Из-за свойства scaleAspectFit в contentMode, изображение может не заполнять весь экран, будут видны белые полоски:
<img width="510" alt="Screenshot 2022-10-05 at 09 40 01" src="https://user-images.githubusercontent.com/20269264/193989342-dffd71e9-1382-4a2d-a70d-50989d9a33a8.png">

2022-10-05 05:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
здесь нужны табы, чтобы не делать это вручную, выделите весь файл и зажмите _control + i_
```suggestion
        if correctCurrentAnswer {
                showAnswerResult(isCorrect: true)
        } else {
                showAnswerResult(isCorrect: false)
        }
```

2022-10-05 05:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 20
cornerRadius и masksToBounds - разовые настройки, их можно делать один раз в сториборде или во viewDidLoad. 

Сейчас при старте приложения, у постера нет скруглений, давайте исправим это
<img width="510" alt="Screenshot 2022-10-05 at 09 39 21" src="https://user-images.githubusercontent.com/20269264/193989638-39112081-7d9a-47a8-af16-865e8038bb5d.png">

2022-10-05 11:00 UTC, RdDevi1 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 20
Александра, большое спасибо за подробное ревью) Можно еще уточнить, где все же лучше указывать эти разовые параметры? верно понимаю, что если с ними в дальнейшем работы в коде не происходит - лучше их указать в сториборде чтобы на них не отвлекаться?

2022-10-05 11:12 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 20
В сториборде вы можете делать так:
- в качестве imageView.layer.masksToBounds = true, 
- аналогом служит галка у свойства clipsToBounds(или свойством, как у вас),
- а округление только в key path блоке layer.cornerRadius (ка у вас и сделано). 

Получается если вы это сделали в сториборде, то в коде не надо. И наоборот. 
Если настраиваете через код - то в функции viewDidLoad. 

По поводу того, какой способ выбирать, то делайте как вам в учебнике говорят. Вы сейчас учитесь работать со сторибордами. В продакшене разные подходы используют: и кодом верстают, и только сторибордами(xib), и смешанный подход используется. Личное я не очень приветствую использование key path в сториборде, потому что именно такие настройки сложнее масштабировать и ревьювить (если вы заметили, сториборд это не код, а xml-форматированный документ). Читать на ревью ксибы обычно сложно.

2022-10-05 12:11 UTC, merged