Sprint 05
RdDevi1/MovieQuiz-ios pull request #4
Opened 2022-10-18 11:59 UTC by RdDevi1

Выполнено задание по Спринт_5

2022-10-18 14:22 UTC, ABashkirova requested changes

2022-10-18 14:22 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    private let questions: [QuizQuestion] = [
Давайте соблюдать порядок:

1) переменные, 2) функции

среди переменных порядок тоже наводить: публичные,  приватные

Среди функций: инит, публичные, приватные

2022-10-18 14:22 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +protocol StatisticService {
А где StatisticServiceImplementation?

2022-10-19 07:49 UTC, RdDevi1 commented on MovieQuiz/Services/StatisticService.swift
> +protocol StatisticService {
Добрый день, не совсем понял почему не хватает файлов, класс StatisticServiceImplementation расположен в одноименном файле в папке services. еще раз закомметил и запушил изменения с переменными и функциями. В случае повторной ошибки создам новый PR. Еще хотел бы узнать есть ли удобный способ сделать вызов рандомных вопросов из массива не повторяющимся? на stackoverflow найденный варианты больше похожи на "костыли"

2022-10-19 08:00 UTC, ABashkirova commented on MovieQuiz/Services/StatisticService.swift
> +protocol StatisticService {
Да, теперь всех файлов хватает для компиляции, спасибо

> Еще хотел бы узнать есть ли удобный способ сделать вызов рандомных вопросов из массива не повторяющимся? на stackoverflow найденный варианты больше похожи на "костыли"

Не совсем понимаю, что вы называете костылями.
Чтобы исключить повторы, нужно чтобы при получении элемента из коллекции, он из нее извлекался. 
Вы можете перемешать(shuffle) исходные элементы, чтобы имитировать рандомность полученного элемента, и за тем доставать элементы с последующим удалением их из коллекции.  
При этом надо понимать, что нужна и исходная коллекция, чтобы у вас не получилось так, что ко второму квизу не останется вопросов.

2022-10-19 08:03 UTC, ABashkirova approved these changes

2022-10-19 09:00 UTC, merged