Sprint 06
RdDevi1/MovieQuiz-ios pull request #5
Opened 2022-10-24 12:55 UTC by RdDevi1

Выполнены задания по спринту 6

2022-10-24 14:23 UTC, mmbabaev requested changes

2022-10-24 14:23 UTC, mmbabaev commented on MovieQuiz/Services/NetworkClient.swift
> +//        public enum Result<Success, Failure> where Failure : Error {
лучше убрать комментарий

2022-10-24 14:23 UTC, mmbabaev commented on MovieQuiz/Services/QuestionFactory.swift
> +            let text = questionsArray.randomElement()!
избегайте force unwrap

2022-10-24 14:23 UTC, mmbabaev commented on MovieQuiz/Services/QuestionFactory.swift
> +            //        let index = (0..<questions.count).randomElement() ?? 0
cнова комментарии в коде

2022-10-24 14:23 UTC, mmbabaev commented on MovieQuiz/Services/QuestionFactory.swift
> +                if rating > 8.5 && text == "Рейтинг этого фильма больше чем 8,5?" {
строки повторяются, выносите в константы (отдельные переменные)

2022-10-24 14:23 UTC, mmbabaev commented on MovieQuiz/Services/QuestionFactory.swift
> +                    return true
Интересная идея

2022-10-24 14:23 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.present(self, animated: true, completion: nil)
тут непонятно что происходит - мы говорим контроллеру показать самого себя? 

Должна происходить повторная попытка загрузить данные

2022-10-24 20:13 UTC, RdDevi1 commented on MovieQuiz/Services/QuestionFactory.swift
> +                    return true
единственная идея где совпало "придумано" и "реализовано" ))

2022-10-24 20:16 UTC, RdDevi1 commented on MovieQuiz/Services/QuestionFactory.swift
> +            let text = questionsArray.randomElement()!
решил не распаковывать изначально потому что беру данные из массива, который не формируется в процессе выполнения программы, а уже целиком известен и записан + константа. В таких случаях также лучше избегать force unwrap?

2022-10-25 10:07 UTC, mmbabaev commented on MovieQuiz/Services/QuestionFactory.swift
> +            let text = questionsArray.randomElement()!
согласен с вами, можно оставить) 
 

Вообще мне кажется тут спорный момент, в реальном проекте я бы не стал все равно делать форс анрап с мыслью, что код может позже быть изменен и переменная перестанет быть константой.

2022-10-25 10:16 UTC, mmbabaev requested changes

2022-10-25 10:16 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.questionFactory?.loadData()
этот completion не вызывается

2022-10-25 10:16 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.questionFactory?.loadData()
в AlertPresenter не вызывается  `model.completion `

2022-10-25 14:27 UTC, RdDevi1 commented on MovieQuiz/Services/QuestionFactory.swift
> +            let text = questionsArray.randomElement()!
Это и хотел уточнить) суть понял - буду акцентировать внимание на распаковке

2022-10-25 18:10 UTC, merged